### ISSUE TITLE
Concoct error

### ISSUE THREAD

**Issue by AroneyS** [rhysnewell/aviary#108]
Concoct failed for ~20 single-sample recovery with the following error. Is it something about contig names? I had to rerun concoct manually to get the error since stderr is sent to `/dev/null` and this error at least wasn't in concoct's `log.txt`.

```python
Traceback (most recent call last):
  File "/home/aroneys/m/users/aroneys/.conda/envs/00d91568b98b8a6967e97dcf18eb70ed_/bin/concoct", line 90, in <module>
    results = main(args)
  File "/home/aroneys/m/users/aroneys/.conda/envs/00d91568b98b8a6967e97dcf18eb70ed_/bin/concoct", line 37, in main
    transform_filter, pca = perform_pca(
  File "/home/aroneys/m/users/aroneys/.conda/envs/00d91568b98b8a6967e97dcf18eb70ed_/lib/python3.10/site-packages/concoct/transform.py", line 5, in perform_pca
    pca_object = PCA(n_components=nc, random_state=seed).fit(d)
  File "/home/aroneys/m/users/aroneys/.conda/envs/00d91568b98b8a6967e97dcf18eb70ed_/lib/python3.10/site-packages/sklearn/base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/aroneys/m/users/aroneys/.conda/envs/00d91568b98b8a6967e97dcf18eb70ed_/lib/python3.10/site-packages/sklearn/decomposition/_pca.py", line 434, in fit
    self._fit(X)
  File "/home/aroneys/m/users/aroneys/.conda/envs/00d91568b98b8a6967e97dcf18eb70ed_/lib/python3.10/site-packages/sklearn/decomposition/_pca.py", line 483, in _fit
    X = self._validate_data(
  File "/home/aroneys/m/users/aroneys/.conda/envs/00d91568b98b8a6967e97dcf18eb70ed_/lib/python3.10/site-packages/sklearn/base.py", line 579, in _validate_data
    self._check_feature_names(X, reset=reset)
  File "/home/aroneys/m/users/aroneys/.conda/envs/00d91568b98b8a6967e97dcf18eb70ed_/lib/python3.10/site-packages/sklearn/base.py", line 440, in _check_feature_names
    feature_names_in = _get_feature_names(X)
  File "/home/aroneys/m/users/aroneys/.conda/envs/00d91568b98b8a6967e97dcf18eb70ed_/lib/python3.10/site-packages/sklearn/utils/validation.py", line 2021, in _get_feature_names
    raise TypeError(
TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.
```

**Comment by rhysnewell** [comment]
Have you check the contig names that get produced in the concoct coverage table? Are some of them appearing as just raw numbers without any extra fluff? 

Btw, although annoying concoct stderr gets piped to /dev/null because it is really verbose and it would start causing severe runtime issues if it was left to continue chirping

**Comment by AroneyS** [comment]
They are all things like: `NODE_3536854_length_56_cov_1.000000.concoct_part_0`

**Comment by AroneyS** [comment]
https://github.com/BinPro/CONCOCT/issues/323#issuecomment-1449061356

**Comment by rhysnewell** [comment]
See https://github.com/rhysnewell/aviary/pull/107 for implemented fix
