### ISSUE TITLE
AttributeError: 'InputFiles' object has no attribute 'flye_fasta'

### ISSUE THREAD

**Issue by sternp** [rhysnewell/aviary#117]
Hey Rhys, can you have a quick look at this please? This is aviary-v0.7.0

Cheers

```Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 64
Rules claiming more threads will be scaled down.
Provided resources: mem_mb=512000
Job stats:
job                          count    min threads    max threads
-------------------------  -------  -------------  -------------
combine_long_only                1             64             64
complete_assembly_with_qc        1              1              1
complete_qc_long                 1              1              1
fastqc_long                      1             64             64
get_bam_indices                  1             64             64
nanoplot                         1             64             64
prepare_binning_files            1             64             64
total                            7              1             64

Select jobs to execute...

[Thu Aug 24 08:42:27 2023]
rule combine_long_only:
    input: data/long_reads.fastq.gz, data/assembly.pol.rac.fasta
    output: data/final_contigs.fasta
    jobid: 6
    reason: Missing output files: data/final_contigs.fasta
    priority: 1
    threads: 64
    resources: tmpdir=/data1/tmp

Activating conda environment: ../../../../conda/72b7ceb517d69ea6d06efe462d7cb2a8
Traceback (most recent call last):
  File "/mnt/hpccs01/work/microbiome/gordon/nanopore_assembly/aviary_output/barcode1/.snakemake/scripts/tmphnizu5uw.combine_assemblies.py", line 27, in <module>
    flye_fasta = snakemake.input.flye_fasta
AttributeError: 'InputFiles' object has no attribute 'flye_fasta'
[Thu Aug 24 08:42:29 2023]
Error in rule combine_long_only:
    jobid: 6
    output: data/final_contigs.fasta
    conda-env: /mnt/hpccs01/work/microbiome/conda/72b7ceb517d69ea6d06efe462d7cb2a8

RuleException:
CalledProcessError in line 668 of /mnt/hpccs01/work/microbiome/sw/aviary_repos/aviary-v0.7.0/aviary/aviary/modules/assembly/assembly.smk:
Command 'source /mnt/hpccs01/work/microbiome/conda/envs/aviary-v0.7.0/bin/activate '/mnt/hpccs01/work/microbiome/conda/72b7ceb517d69ea6d06efe462d7cb2a8'; set -euo pipefail;  /mnt/hpccs01/work/microbiome/conda/envs/aviary-v0.7.0/bin/python3.10 /mnt/hpccs01/work/microbiome/gordon/nanopore_assembly/aviary_output/barcode1/.snakemake/scripts/tmphnizu5uw.combine_assemblies.py' returned non-zero exit status 1.
  File "/mnt/hpccs01/work/microbiome/sw/aviary_repos/aviary-v0.7.0/aviary/aviary/modules/assembly/assembly.smk", line 668, in __rule_combine_long_only
  File "/mnt/hpccs01/work/microbiome/conda/envs/aviary-v0.7.0/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
An error occurred
Complete log: .snakemake/log/2023-08-24T084209.654852.snakemake.log
08/24/2023 08:42:29 AM INFO: Finished: get_bam_indices
08/24/2023 08:42:29 AM INFO: Executing: snakemake --snakefile /mnt/hpccs01/work/microbiome/sw/aviary_repos/aviary-v0.7.0/aviary/aviary/modules/Snakefile --directory /home/sternesp/microbiome/gordon/nanopore_assembly/aviary_output/barcode1 --cores 64 --rerun-incomplete   --configfile /home/sternesp/microbiome/gordon/nanopore_assembly/aviary_output/barcode1/config.yaml --nolock  --conda-frontend mamba --resources mem_mb=512000   --use-conda --conda-prefix /mnt/hpccs01/work/microbiome/conda   recover_mags
```

**Comment by rhysnewell** [comment]
Hey Peter,

Sure thing I see what has happened, should be a quick fix give me a minute
