### ISSUE TITLE
Undefined variable error in 0.8.0

### ISSUE THREAD

**Issue by Ge0rges** [rhysnewell/aviary#143]
Fresh install of 0.8.0 using pip. I run `aviary configure -o logs/ --eggnog-db-path ../databases/eggnog/ --gtdb-path ../databases/gtdb/ --checkm2-db-path  ../databases/checkm2db/ --download`

```                                                                                                                   
09/13/2023 01:11:24 AM INFO: Time - 01:11:24 13-09-2023                                                                                                       
09/13/2023 01:11:24 AM INFO: Command - /Accounts/gkanaan/.conda/envs/aviary/bin/aviary configure -o logs/ --eggnog-db-path ../databases/eggnog/ --gtdb-path ..
/databases/gtdb/ --checkm2-db-path ../databases/checkm2db/ --download                                                                                         
09/13/2023 01:11:24 AM INFO: Version - 0.8.0                                                                                                                  
09/13/2023 01:11:24 AM INFO: The current aviary environment variables are:                                                                                    
09/13/2023 01:11:24 AM INFO: CONDA_ENV_PATH: /Accounts/gkanaan/.conda/envs
09/13/2023 01:11:24 AM INFO: TMPDIR: /tmp
09/13/2023 01:11:24 AM INFO: GTDBTK_DATA_PATH: ../databases/gtdb/
09/13/2023 01:11:24 AM INFO: EGGNOG_DATA_DIR: ../databases/eggnog/
09/13/2023 01:11:24 AM INFO: CHECKM2DB: ../databases/checkm2db/
Traceback (most recent call last):
  File "/Accounts/gkanaan/.conda/envs/aviary/lib/python3.11/site-packages/aviary/modules/processor.py", line 141, in __init__
    self.reference_filter = [os.path.abspath(ref_fil) for ref_fil in args.reference_filter if ref_fil != 'none']
                                                                     ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'reference_filter'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Accounts/gkanaan/.conda/envs/aviary/bin/aviary", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Accounts/gkanaan/.conda/envs/aviary/lib/python3.11/site-packages/aviary/aviary.py", line 1198, in main                                              
    processor = Processor(args)
                ^^^^^^^^^^^^^^^
  File "/Accounts/gkanaan/.conda/envs/aviary/lib/python3.11/site-packages/aviary/modules/processor.py", line 154, in __init__                                
    self.min_read_size = args.min_read_size
                         ^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'min_read_size'
```

It seems that in your `try: except:` block the `args.min_read_size` is undefined. In fact that whole block looks like it shouldn't be called under `configure` so I made a small local fix checking for that and setting these to random values for now that would break my workflow if they were incorrectly hit (0s).

**Comment by rhysnewell** [comment]
Huh, damn. So this error only occurs during calls to `configure`?

**Comment by Ge0rges** [comment]
Seems like it, at least when trying with variations of assemble.
