### ISSUE TITLE
Error in singlem log

### ISSUE THREAD

**Issue by Ge0rges** [rhysnewell/aviary#152]
I was going through results and found this error in the singlem log file.

```
09/15/2023 03:19:36 AM INFO: Using as input 24 different sequence files e.g. bins/final_bins/concoct_bins.tsv.017_sub.fna
09/15/2023 03:19:36 AM INFO: Searching with 14 SingleM package(s)
09/15/2023 03:19:36 AM INFO: Searching for reads matching 28 different protein HMM(s)
09/15/2023 03:20:59 AM INFO: Finished search phase
09/15/2023 03:20:59 AM INFO: Running separate alignments in GraftM..
09/15/2023 03:22:31 AM INFO: Finished extracting aligned sequences
09/15/2023 03:22:31 AM INFO: Running taxonomic assignment with GraftM..
09/15/2023 03:34:44 AM INFO: Finished running taxonomic assignment with GraftM
09/15/2023 03:34:45 AM INFO: Finished
09/15/2023 03:34:50 AM INFO: Using as input 1 different sequence files e.g. /localdata/researchdrive/gkanaan/seaice_methylation/medaka/consensus.fasta
09/15/2023 03:34:50 AM INFO: Searching with 14 SingleM package(s)
09/15/2023 03:34:50 AM INFO: Searching for reads matching 28 different protein HMM(s)
09/15/2023 03:36:49 AM INFO: Finished search phase
09/15/2023 03:36:49 AM INFO: Running separate alignments in GraftM..
09/15/2023 03:37:41 AM INFO: Finished extracting aligned sequences
09/15/2023 03:37:41 AM INFO: Running taxonomic assignment with GraftM..
09/15/2023 03:51:06 AM INFO: Finished running taxonomic assignment with GraftM
09/15/2023 03:51:07 AM INFO: Finished
09/15/2023 03:51:12 AM INFO: Read in 186 markers from the different genomes
09/15/2023 03:51:12 AM INFO: After excluding duplicate markers that may indicate contamination, found 118 markers
09/15/2023 03:51:12 AM INFO: Read in 118 unique sequences from the 20 reference genomes
Traceback (most recent call last):
  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/bin/singlem", line 744, in <module>
    output_svg=args.plot)
  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/appraisal_result.py", line 71, in plot
    genes_to_plot = [self._pick_representative_marker(doing_assembly, doing_binning)]
  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/appraisal_result.py", line 167, in _pick_representative_marker
    key = lambda marker: sum(marker_to_distances[marker]))
ValueError: min() arg is an empty sequence
```

The singlem_reads log file also contained errors:
```
Using prexisting directory: data/singlem_out/
09/14/2023 08:25:25 PM INFO: Using as input 6 different sequence files e.g. /localdata/researchdrive/gkanaan/seaice_methylation/fastqs/decontaminated/barcode01/barcode01.fastq
09/14/2023 08:25:25 PM INFO: Searching with 14 SingleM package(s)
09/14/2023 08:25:25 PM INFO: Searching for reads matching 28 different protein HMM(s)
Traceback (most recent call last):
  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/bin/singlem", line 513, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/pipe.py", line 45, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/pipe.py", line 176, in run_to_otu_table
    search_result = self._search(hmms, forward_read_files, reverse_read_files)
  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/pipe.py", line 860, in _search
    run(hmms, graftm_protein_search_directory, True)
  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/pipe.py", line 848, in run
    extern.run(cmd)
  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/extern/__init__.py", line 41, in run
    raise ExternCalledProcessError(process, command)
extern.ExternCalledProcessError: Command graftM graft --verbosity 2 --input_sequence_type nucleotide  --min_orf_length 96   --filter_minimum 28 --threads 10 --forward /localdata/researchdrive/gkanaan/seaice_methylation/fastqs/decontaminated/barcode01/barcode01.fastq /localdata/researchdrive/gkanaan/seaice_methylation/fastqs/decontaminated/barcode02/barcode02.fastq /localdata/researchdrive/gkanaan/seaice_methylation/fastqs/decontaminated/barcode03/barcode03.fastq /localdata/researchdrive/gkanaan/seaice_methylation/fastqs/decontaminated/barcode05/barcode05.fastq /localdata/researchdrive/gkanaan/seaice_methylation/fastqs/decontaminated/barcode06/barcode06.fastq /localdata/researchdrive/gkanaan/seaice_methylation/fastqs/decontaminated/barcode07/barcode07.fastq --search_only --search_hmm_files /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.1.ribosomal_protein_L2_rplB.gpkg.spkg/S1.1.ribosomal_protein_L2_rplB/graftmUShLiV_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.1.ribosomal_protein_L2_rplB.gpkg.spkg/S1.1.ribosomal_protein_L2_rplB/graftmY0W8yc_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.10.ribosomal_protein_S7.gpkg.spkg/S1.10.ribosomal_protein_S7/graftmunofJO_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.10.ribosomal_protein_S7.gpkg.spkg/S1.10.ribosomal_protein_S7/graftmvR14Hx_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ/graftme9CA2v_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ/graftmmSefD1_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.12.ribosomal_protein_S12_S23.gpkg.spkg/S1.12.ribosomal_protein_S12_S23/graftmD68DOf_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.12.ribosomal_protein_S12_S23.gpkg.spkg/S1.12.ribosomal_protein_S12_S23/graftm4bucq1_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.13.ribosomal_protein_S15P_S13e.gpkg.spkg/S1.13.ribosomal_protein_S15P_S13e/graftmSIv4ri_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.13.ribosomal_protein_S15P_S13e.gpkg.spkg/S1.13.ribosomal_protein_S15P_S13e/graftmh8KCUY_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftm5WU6Uq_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftmSHqOh3_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.2.ribosomal_protein_L3_rplC.gpkg.spkg/S1.2.ribosomal_protein_L3_rplC/graftmeZ00Qg_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.2.ribosomal_protein_L3_rplC.gpkg.spkg/S1.2.ribosomal_protein_L3_rplC/graftmID8t_I_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.3.ribosomal_protein_L5_rplE.gpkg.spkg/S1.3.ribosomal_protein_L5_rplE/graftmFIm7K0_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.3.ribosomal_protein_L5_rplE.gpkg.spkg/S1.3.ribosomal_protein_L5_rplE/graftmMH5eE7_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.4.ribosomal_protein_L6_rplF.gpkg.spkg/S1.4.ribosomal_protein_L6_rplF/graftmDE7_8b_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.4.ribosomal_protein_L6_rplF.gpkg.spkg/S1.4.ribosomal_protein_L6_rplF/graftmr_l5Gy_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.5.ribosomal_protein_L11_rplK.gpkg.spkg/S1.5.ribosomal_protein_L11_rplK/graftmCpbnSc_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.5.ribosomal_protein_L11_rplK.gpkg.spkg/S1.5.ribosomal_protein_L11_rplK/graftm5YNr6y_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.6.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/S1.6.ribosomal_protein_L14b_L23e_rplN/graftmAiWqW8_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.6.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/S1.6.ribosomal_protein_L14b_L23e_rplN/graftmIkMbHN_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.7.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/S1.7.ribosomal_protein_L16_L10E_rplP/graftmAbXN7F_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.7.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/S1.7.ribosomal_protein_L16_L10E_rplP/graftmWRo94z_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.8.ribosomal_protein_S2_rpsB.gpkg.spkg/S1.8.ribosomal_protein_S2_rpsB/graftmhZA_92_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.8.ribosomal_protein_S2_rpsB.gpkg.spkg/S1.8.ribosomal_protein_S2_rpsB/graftmrgaTTv_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftm4ehmqY_search.hmm /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftmBf7aFs_search.hmm --output_directory /dev/shm/tmpihp_m86o/graftm_protein_search --aln_hmm_file /Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/data/S1.1.ribosomal_protein_L2_rplB.gpkg.spkg/S1.1.ribosomal_protein_L2_rplB/graftmUShLiV_search.hmm  returned non-zero exit status 1.
STDERR was: b'Traceback (most recent call last):\n  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/bin/graftM", line 415, in <module>\n    Run(args).main()\n  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/graftm/run.py", line 613, in main\n    self.graft()\n  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/graftm/run.py", line 388, in graft\n    diamond_db\n  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/graftm/timeit.py", line 10, in timed\n    result = method(*args, **kw)\n  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 851, in aa_db_search\n    hit_reads_orfs_fasta)\n  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 943, in search_and_extract_orfs_matching_protein_database\n    hits\n  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 534, in _extract_from_raw_reads\n    extern.run(extract_cmd, stdin=\'\\n\'.join(input_reads))\n  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/extern/__init__.py", line 41, in run\n    raise ExternCalledProcessError(process, command)\nextern.ExternCalledProcessError: Command mfqe --output-uncompressed --fasta-read-name-lists /dev/stdin --input-fasta <(awk \'{print ">" substr($0,2);getline;print;getline;getline}\' \'/localdata/researchdrive/gkanaan/seaice_methylation/fastqs/decontaminated/barcode01/barcode01.fastq\') --output-fasta-files \'/dev/shm/tmpihp_m86o/tempfiles/_raw_extracted_reads.faxov1su33\' returned non-zero exit status 101.\nSTDERR was: b"[2023-09-15T01:31:26Z INFO  mfqe] Read in 1492 read names from /dev/stdin\\n[2023-09-15T01:31:26Z INFO  mfqe] Iterating input FASTQ file\\n[2023-09-15T01:31:31Z INFO  mfqe] Extracted 0 reads from 1004384 total\\nthread \'main\' panicked at \'Mismatching numbers of read names were observed. Expected:\\n[1492]\\nbut found\\n[0]\', src/main.rs:333:9\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\\n"STDOUT was: b\'\'\n'STDOUT was: b''
usage: singlem summarise [-h] [--debug] [--version] [--quiet] [--full_help]
                         [--input_archive_otu_tables INPUT_ARCHIVE_OTU_TABLES [INPUT_ARCHIVE_OTU_TABLES ...]]
                         [--input_otu_tables INPUT_OTU_TABLES [INPUT_OTU_TABLES ...]]
                         [--cluster] [--cluster_id CLUSTER_ID]
                         [--taxonomy TAXONOMY]
                         [--rarefied_output_otu_table RAREFIED_OUTPUT_OTU_TABLE]
                         [--number_to_choose NUMBER_TO_CHOOSE]
                         [--collapse_coupled]
                         [--output_otu_table OUTPUT_OTU_TABLE]
                         [--output_extras] [--krona KRONA]
                         [--wide_format_otu_table WIDE_FORMAT_OTU_TABLE]
                         [--strain_overview_table STRAIN_OVERVIEW_TABLE]
                         [--unifrac_by_otu UNIFRAC_BY_OTU]
                         [--unifrac_by_taxonomy UNIFRAC_BY_TAXONOMY]
                         [--biom_prefix BIOM_PREFIX]
                         [--clustered_output_otu_table CLUSTERED_OUTPUT_OTU_TABLE]
singlem summarise: error: argument --input_otu_tables: expected at least one argument
```

**Comment by rhysnewell** [comment]
@wwood Any idea with singleM?

**Comment by Ge0rges** [comment]
Just wanted to mention that I was able to reproduce these errors consistently when running aviary on a given set of files.

**Comment by rhysnewell** [comment]
I believe this is likely an issue with singlem and not aviary, something about these samples/bins/assembly that singlem doesn't like

**Comment by Ge0rges** [comment]
Should I open an issue on the singlem github?

**Comment by rhysnewell** [comment]
I've tagged the singlem dev in this thread already, I'll mention it to him when I speak to him next. You might get a faster response if you open another issue mentioning this issue
