### ISSUE TITLE
lorikeet error

### ISSUE THREAD

**Issue by gbouras13** [rhysnewell/aviary#58]
Hi Rhys,

Sorry for the spam - I have another issue with lorikeet.

I am running short read mode only.

(after fixing the typo with #56) I get the following error:

rule lorikeet:
    input: bins/final_bins
    output: strain_diversity
    jobid: 0
    reason: Missing output files: strain_diversity
    threads: 32
    resources: tmpdir=/hpcfs/users/a1667917/tmp

Activating conda environment: ../../../myconda/envs/aviary/fcd3e55b2a2091296105e8c2f42ee964
Activating conda environment: ../../../myconda/envs/aviary/fcd3e55b2a2091296105e8c2f42ee964
[2022-07-21T02:28:13Z INFO  lorikeet] lorikeet version 0.7.1
[2022-07-21T02:28:13Z INFO  lorikeet_genome] Using min-read-aligned-percent 0%
[2022-07-21T02:28:13Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/.snakemake_timestamp' as a genome FASTA file
[2022-07-21T02:28:14Z INFO  lorikeet_genome::utils::utils] Not pre-generating minimap2 index
[2022-07-21T02:28:14Z WARN  lorikeet_genome::utils::utils] Not using reference index...
[2022-07-21T02:28:14Z INFO  lorikeet_genome::processing::lorikeet_engine] Processing short reads...
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/haplotype/haplotype_caller_engine.rs:305:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/haplotype/haplotype_caller_engine.rs:305:14
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/haplotype/haplotype_caller_engine.rs:305:14
thread '<unnamed>' panicked at 'thread 'called `Option::unwrap()` on a `None` value<unnamed>', ' panicked at 'src/haplotype/haplotype_caller_engine.rscalled `Option::unwrap()` on a `None` value:', 305src/haplotype/haplotype_caller_engine.rs::14thread '
<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/haplotype/haplotype_caller_engine.rs:305:14305:14

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/haplotype/haplotype_caller_engine.rsthread ':<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/haplotype/haplotype_caller_engine.rs:305:14
305:14

I also get the same error when I run lorikeet manually like e.g.

lorikeet evolve -t 32 -d "/hpcfs/users/a1667917/Kevin/aviary/S1/bins/final_bins" -x "fna" \
-p 8 -1 $FASTQ_DIR/Illumina_bacteria_fastp_R1.fastq.gz -2 $FASTQ_DIR/Illumina_bacteria_fastp_R2.fastq.gz  -o lorikeet_test

I can confirm that the "S1/bins/final_bins" has a symlink that points to non-empty .fna bins which seem fine.

George

**Comment by rhysnewell** [comment]
Hi George,

This is an odd one, looks like one of the command line arguments in the Lorikeet CLI got accidentally deleted before the release of 0.7.1 causing it to crash when you use the evolve subcommand. Could you just try using `lorikeet call` instead and see if it still crashes?

**Comment by rhysnewell** [comment]
If you want the output from evolve you can use `lorikeet call` followed by `lorikeet evolve` pointing to the same output directory with the same input and it will just re-use the variants created by `call`. I'll have to make a new conda release to make `evolve` work without having to run call first, my bad

**Comment by gbouras13** [comment]
Hi Rhys,

I have re-installed aviary with the latest commits and ran it from scratch.

I am still an error with Lorikeet:

[2022-07-21T07:24:45Z INFO  lorikeet] lorikeet version 0.7.1
[2022-07-21T07:24:45Z INFO  lorikeet_genome] Using min-covered-fraction 0%
[2022-07-21T07:24:45Z INFO  lorikeet_genome] Using min-read-aligned-percent 0%
[2022-07-21T07:24:45Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/.snakemake_timestamp' as a genome FASTA file
[2022-07-21T07:24:45Z INFO  lorikeet_genome::utils::utils] Not pre-generating minimap2 index
[2022-07-21T07:24:45Z WARN  lorikeet_genome::utils::utils] Not using reference index...
[2022-07-21T07:24:47Z INFO  lorikeet_genome::processing::lorikeet_engine] Processing short reads...
[2022-07-21T07:26:52Z INFO  lorikeet] lorikeet version 0.7.1
[2022-07-21T07:26:52Z INFO  lorikeet_genome] Using min-read-aligned-percent 0%
[2022-07-21T07:26:52Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/metabat_bins_sspec.tsv.006.fna.fai' as a genome FASTA file, as it does not end with the extension '.fna'
[2022-07-21T07:26:52Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/metabat2_refined_bins.tsv.004.fna.fai' as a genome FASTA file, as it does not end with the extension '.fna'
[2022-07-21T07:26:52Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/semibin_refined_bins.tsv.008.fna.fai' as a genome FASTA file, as it does not end with the extension '.fna'
[2022-07-21T07:26:52Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/concoct_bins.tsv.004.fna.fai' as a genome FASTA file, as it does not end with the extension '.fna'
[2022-07-21T07:26:52Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/.snakemake_timestamp' as a genome FASTA file
[2022-07-21T07:26:52Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/semibin_refined_bins.tsv.005.fna.fai' as a genome FASTA file, as it does not end with the extension '.fna'
[2022-07-21T07:26:52Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/metabat2_refined_bins.tsv.007.fna.fai' as a genome FASTA file, as it does not end with the extension '.fna'
[2022-07-21T07:26:52Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/rosella_refined_bins.tsv.018_sub.fna.fai' as a genome FASTA file, as it does not end with the extension '.fna'
[2022-07-21T07:26:52Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/semibin_refined_bins.tsv.003.fna.fai' as a genome FASTA file, as it does not end with the extension '.fna'
[2022-07-21T07:26:52Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/concoct_bins.tsv.003_sub.fna.fai' as a genome FASTA file, as it does not end with the extension '.fna'
[2022-07-21T07:26:52Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/maxbin_bins.tsv.006_sub.fna.fai' as a genome FASTA file, as it does not end with the extension '.fna'
[2022-07-21T07:26:52Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/concoct_bins.tsv.006_sub.fna.fai' as a genome FASTA file, as it does not end with the extension '.fna'
[2022-07-21T07:26:52Z INFO  bird_tool_utils::clap_utils] Not using directory entry 'bins/final_bins/metabat2_refined_bins.tsv.008.fna.fai' as a genome FASTA file, as it does not end with the extension '.fna'
[2022-07-21T07:26:52Z INFO  lorikeet_genome::utils::utils] Not pre-generating minimap2 index
[2022-07-21T07:26:52Z WARN  lorikeet_genome::utils::utils] Not using reference index...
[2022-07-21T07:26:53Z INFO  lorikeet_genome::processing::lorikeet_engine] Processing short reads...
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/haplotype/haplotype_caller_engine.rs:305:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Same as if I try and run it manually

lorikeet call -t 32 -d "/hpcfs/users/a1667917/Kevin/aviary/S1/bins/final_bins" -x "fna"    \
-p 8 -1 $FASTQ_DIR/Illumina_bacteria_fastp_R1.fastq.gz -2 $FASTQ_DIR/Illumina_bacteria_fastp_R2.fastq.gz  -o lorikeet_test

lorikeet evolve -t 32 -d "/hpcfs/users/a1667917/Kevin/aviary/S1/bins/final_bins" -x "fna"   \
-p 8 -1 $FASTQ_DIR/Illumina_bacteria_fastp_R1.fastq.gz -2 $FASTQ_DIR/TCGA-CV-7090-01A-11D-2276-Illumina_bacteria_fastp_R2.fastq.gz  -o lorikeet_test

`lorikeet call` seems to have worked - the output dir has a strain_diversity dir with directories for each bin, with anis and vcf files.

George

**Comment by rhysnewell** [comment]
Dang, alright I'll fix this tomorrow. Really not sure what happened to that release of Lorikeet, but I'll fix it up and close it when it's all done.

The diversity module only got added properly to aviary a couple of days ago so I haven't been able to test it properly, so you've kind of been an involuntary guinea pig. Maybe just stick to the other modules for now, and I'll close this when diversity is ready

Rhys

**Comment by gbouras13** [comment]
No rush on it Rhys at all! Just wanted to alter you to the error, it's probably a bit of overkill for my analysis anyway.

The rest runs smoothly for now (except VAMB, but that never works in these pipelines for me I find so I just skipped it, great feature that you can do that) - thanks for putting it all together, it is extremely easy for me to install and use.

George
