### ISSUE TITLE
configure: Namespace error

### ISSUE THREAD

**Issue by wwood** [rhysnewell/aviary#70]
This is with current main branch

```
(aviary_after_0.4.3_conda_env)cl5n008:20220828:~/m/red_sea/4_individual_assemblies$ aviary configure --gtdb-path ~/m/db/gtdb/gtdb_release207_v2/ --eggnog-db-path ~/m/db/eggnog-mapper/2.1.9 --checkm2-db-path ~/m/db/CheckM2_database/
08/28/2022 06:54:29 AM INFO: Time - 06:54:29 28-08-2022
08/28/2022 06:54:29 AM INFO: Command - /mnt/hpccs01/work/microbiome/red_sea/4_individual_assemblies/aviary_after_0.4.3_conda_env/bin/aviary configure --gtdb-path /home/woodcrob/m/db/gtdb/gtdb_release207_v2/ --eggnog-db-path /home/woodcrob/m/db/eggnog-mapper/2.1.9 --checkm2-db-path /home/woodcrob/m/db/CheckM2_database/
08/28/2022 06:54:29 AM INFO: Version - 0.4.3
Traceback (most recent call last):
  File "/mnt/hpccs01/work/microbiome/red_sea/4_individual_assemblies/aviary/aviary/modules/processor.py", line 161, in __init__
    self.short_percent_identity = args.short_percent_identity
AttributeError: 'Namespace' object has no attribute 'short_percent_identity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/hpccs01/work/microbiome/red_sea/4_individual_assemblies/aviary_after_0.4.3_conda_env/bin/aviary", line 33, in <module>
    sys.exit(load_entry_point('aviary-genome', 'console_scripts', 'aviary')())
  File "/mnt/hpccs01/work/microbiome/red_sea/4_individual_assemblies/aviary/aviary/aviary.py", line 1037, in main
    processor = Processor(args)
  File "/mnt/hpccs01/work/microbiome/red_sea/4_individual_assemblies/aviary/aviary/modules/processor.py", line 176, in __init__
    logging.info(f"Exception {args.pe1} {args.pe2}")
AttributeError: 'Namespace' object has no attribute 'pe1'
```

**Comment by rhysnewell** [comment]
Ah sorry, that was a debug message I forgot to clean up will fix in a minute
