### ISSUE TITLE
Type error when using Aviary cluster

### ISSUE THREAD

**Issue by sternp** [rhysnewell/aviary#72]
Different to Sam's type error, but you might be able to reproduce this one..

```
aviary cluster \
-t 24 \
-n 24 \
--ani 95 \
--precluster-ani 90 \
--max-contamination 10 \
--min-completeness 90 \
--use-checkm2-scores TRUE \
-i /work/microbiome/human/cognobiome/barlowk/swinburne/2022_july_26/output/BBL5911-PFH5-LFH5_binning/bins/final_bins \
/work/microbiome/human/cognobiome/barlowk/swinburne/2022_july_26/output/BBL4572-PFG9-LFG9_binning/bins/final_bins
```
gives
```
10/12/2022 02:04:18 PM INFO: Time - 14:04:18 12-10-2022
10/12/2022 02:04:18 PM INFO: Command - /mnt/hpccs01/work/microbiome/conda/envs/aviary-v0.5.0/bin/aviary cluster -t 24 -n 24 --ani 95 --precluster-ani 90 --max-contamination 10 --min-completeness 90 --use-checkm2-scores TRUE -i /work/microbiome/human/cognobiome/barlowk/swinburne/2022_july_26/output/BBL5911-PFH5-LFH5_binning/bins/final_bins /work/microbiome/human/cognobiome/barlowk/swinburne/2022_july_26/output/BBL4572-PFG9-LFG9_binning/bins/final_bins /work/microbiome/human/cognobiome/barlowk/swinburne/2022_july_26/output/BBL4573-PFG9-LFG9_binning/bins/final_bins /work/microbiome/human/cognobiome/barlowk/swinburne/2022_july_26/output/BBL4496-PFG9-LFG9_binning/bins/final_bins /work/microbiome/human/cognobiome/barlowk/swinburne/2022_july_26/output/BBL4557-PFG9-LFG9_binning/bins/final_bins
10/12/2022 02:04:18 PM INFO: Version - 0.5.0
Traceback (most recent call last):
  File "/mnt/hpccs01/work/microbiome/conda/envs/aviary-v0.5.0/bin/aviary", line 33, in <module>
    sys.exit(load_entry_point('aviary-genome', 'console_scripts', 'aviary')())
  File "/mnt/hpccs01/work/microbiome/sw/aviary_repos/aviary-v0.5.0/aviary/aviary/aviary.py", line 1059, in main
    processor = Processor(args)
  File "/mnt/hpccs01/work/microbiome/sw/aviary_repos/aviary-v0.5.0/aviary/aviary/modules/processor.py", line 235, in __init__
    self.precluster_ani = fraction_to_percent(args.precluster_ani)
  File "/mnt/hpccs01/work/microbiome/sw/aviary_repos/aviary-v0.5.0/aviary/aviary/modules/processor.py", line 550, in fraction_to_percent
    if val <= 1:
TypeError: '<=' not supported between instances of 'str' and 'int
```

**Comment by sternp** [comment]
These are the problem parameters:

--precluster-ani
--ani

**Comment by rhysnewell** [comment]
Hi Peter,

This is an issue that was fixed in recent versions: https://github.com/rhysnewell/aviary/blob/main/aviary/modules/processor.py#L610

**Comment by sternp** [comment]
False alarm, yes. I just figured that out :) Thanks!
