### ISSUE TITLE
KeyError: 'rerun_trigger' in version 0.5.5 

### ISSUE THREAD

**Issue by sternp** [rhysnewell/aviary#82]
Hey Rhys - trying to --build and get the following:

```11/15/2022 09:04:13 AM INFO: Time - 09:04:13 15-11-2022
11/15/2022 09:04:13 AM INFO: Command - /mnt/hpccs01/work/microbiome/conda/envs/aviary-v0.5.5/bin/aviary complete --pe-1 /home/sternesp/microbiome/human/preeclampsia/preeclampsia/fastq_kneaded/A016w28_R1_kneaddata_paired_1.fastq --pe-2 /home/sternesp/microbiome/human/preeclampsia/preeclampsia/fastq_kneaded/A016w28_R1_kneaddata_paired_2.fastq --max-threads 24 --longreads /home/sternesp/microbiome/sequencing/nanopore_sequencing_summaries/Pr13_290422-long_read_extraction_trial/barcode92.fastq.gz --output A016w2821421.2f22fdg41 --n-cores 24 --build
11/15/2022 09:04:13 AM INFO: Version - 0.5.5
11/15/2022 09:04:13 AM WARNING: No assembly provided, assembly will be created using available reads...
11/15/2022 09:04:13 AM INFO: Configuration file written to /mnt/hpccs01/scratch/microbiome/sternesp/A016w2821421/A016w2821421.2f22fdg41/config.yaml
Traceback (most recent call last):
  File "/mnt/hpccs01/work/microbiome/conda/envs/aviary-v0.5.5/bin/aviary", line 33, in <module>
    sys.exit(load_entry_point('aviary-genome', 'console_scripts', 'aviary')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/hpccs01/work/microbiome/sw/aviary_repos/aviary-v0.5.5/aviary/aviary/aviary.py", line 1140, in main
    processor.run_workflow(cores=int(args.n_cores),
  File "/mnt/hpccs01/work/microbiome/sw/aviary_repos/aviary-v0.5.5/aviary/aviary/modules/processor.py", line 449, in run_workflow
    ).format(
      ^^^^^^^
KeyError: 'rerun_trigger'
```

**Comment by rhysnewell** [comment]
Jeez, sorry pushed that one way too hastily. Was just trying to get the fix released, but I made a typo
