### ISSUE TITLE
Error when running recover pipeline

### ISSUE THREAD

**Issue by 0x1d4e** [rhysnewell/aviary#92]
Hi, during a run of `recover` pipeline, there was an error message in the step 9 (out of 29) `rule checkm_metabat2` concerning about `numpy`: `AttributeError: module 'numpy' has no attribute 'object'`. Aviary was installed using git and with the latest version of 0.5.7. Could you have a look what could be the issue? Thanks a lot.

**Comment by wwood** [comment]
Hi, would you be able to provide a more detailed error please e.g. the stacktrace including the line where the error is occurring?
Thanks.

**Comment by 0x1d4e** [comment]
Hi, thanks a lot for your quick response. Attached please find the log that was produced by `snakemake`. 
[2022-12-21T140500.438575.snakemake.log](https://github.com/rhysnewell/aviary/files/10285807/2022-12-21T140500.438575.snakemake.log)

And the traceback error from the `STDOUT`:
```bash
Activating conda environment: ../../../../home/ubuntu/mambaforge/envs/aviary/2eef2a0892df5690869e1b88d77666ef_
MetaBAT 1 (2.15 (Bioconda)) using p1 95.0%, p2 90.0%, p3 95.0%, minProb 80.0%, minBinned 20%, minCV 1.0, minContig 1500, minContigByCorr 1000, minCorr  0%, paired 0, and 20 bootstrapping
[Info] Correlation binning won't be applied since the number of samples (1) < minSamples (10)
Number of clusters formed: 15
Benchmark: unable to collect cpu and memory benchmark statistics
[Wed Dec 21 14:35:56 2022]
Finished job 12.
9 of 29 steps (31%) done
Select jobs to execute...

[Wed Dec 21 14:35:56 2022]
rule checkm_metabat2:
    input: data/metabat_bins_2/done
    output: data/metabat_bins_2/checkm2_out, data/metabat_bins_2/checkm.out
    jobid: 6
    reason: Missing output files: data/metabat_bins_2/checkm.out; Input files updated by another job: data/metabat_bins_2/done
    threads: 12
    resources: mem_mb=1000, mem_mib=954, disk_mb=1000, disk_mib=954, tmpdir=/tmp

Activating conda environment: ../../../../home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_
Using CheckM2 database /mnt/e/checkm2/CheckM2_database//uniref100.KO.1.dmnd
Traceback (most recent call last):
  File "/usr/local/bin/checkm2", line 27, in <module>
    from checkm2 import predictQuality
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/checkm2/predictQuality.py", line 1, in <module>
    from checkm2 import modelProcessing
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/checkm2/modelProcessing.py", line 17, in <module>
    from tensorflow import keras
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 46, in <module>
    from tensorflow.python import data
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/tensorflow/python/data/__init__.py", line 25, in <module>
    from tensorflow.python.data import experimental
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/tensorflow/python/data/experimental/__init__.py", line 96, in <module>
    from tensorflow.python.data.experimental import service
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 140, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 25, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 20, in <module>
    from tensorflow.python.data.util import structure
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/tensorflow/python/data/util/structure.py", line 26, in <module>
    from tensorflow.python.data.util import nest
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/tensorflow/python/data/util/nest.py", line 41, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/tensorflow/python/framework/sparse_tensor.py", line 29, in <module>
    from tensorflow.python.framework import constant_op
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 29, in <module>
    from tensorflow.python.eager import execute
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 27, in <module>
    from tensorflow.python.framework import dtypes
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py", line 513, in <module>
    np.object,
  File "/home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'object'
[Wed Dec 21 14:36:13 2022]
Error in rule checkm_metabat2:
    jobid: 6
    input: data/metabat_bins_2/done
    output: data/metabat_bins_2/checkm2_out, data/metabat_bins_2/checkm.out
    conda-env: /home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_
    shell:
        touch data/metabat_bins_2/checkm.out; export CHECKM2DB=/mnt/e/checkm2/CheckM2_database//uniref100.KO.1.dmnd; echo "Using CheckM2 database $CHECKM2DB"; checkm2 predict -i data/metabat_bins_2// -x fa -o data/metabat_bins_2/checkm2_out -t 12 --force; cp data/metabat_bins_2/checkm2_out/quality_report.tsv data/metabat_bins_2/checkm.out
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job checkm_metabat2 since they might be corrupted:
data/metabat_bins_2/checkm.out

[Wed Dec 21 17:09:59 2022]
Finished job 10.
10 of 29 steps (34%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
An error occurred
Complete log: .snakemake/log/2022-12-21T140500.438575.snakemake.log
12/21/2022 05:09:59 PM CRITICAL: Command 'snakemake --snakefile /mnt/d/GSN/aviary/aviary/modules/Snakefile --directory /mnt/d/marbles/aviary --jobs 24 --rerun-incomplete   --configfile '/mnt/d/marbles/aviary/config.yaml' --nolock  --conda-frontend mamba --default-resources "tmpdir='/tmp'" --resources mem_mb=256000   --use-conda --conda-prefix /home/ubuntu/mambaforge/envs/aviary/   recover_mags' retu
```

**Comment by rhysnewell** [comment]
The installation of `numpy` may have gotten messed up for whatever reason. You can try activating the `checkm2` conda env: `conda activate ../../../../home/ubuntu/mambaforge/envs/aviary/f9259484cf1638c589c462de9aad1dc6_` and then uninstall numpy:
```
pip uninstall -y numpy
pip uninstall -y setuptools
pip install setuptools
pip install numpy
```

And then try and run aviary again and see if the error pops up again. If it does error out again then I would suspect that it is an error on checkm2's end and you might need to open up an issue over there.

Cheers,
Rhys

**Comment by 0x1d4e** [comment]
Thanks a lot for your help. I tried to uninstall and reinstall `numpy` and `setuptools` in the checkm2 environment. Now it has another error with `concoct` job with the following error message:
```bash
[Mon Jan  2 12:01:59 2023]
rule concoct:
    input: /mnt/d/marbles/assembly/metaSPAdes/sponge_04.scaffolds.metaSPAdes.fasta, data/binning_bams/done
    output: data/concoct_bins/done
    jobid: 9
    benchmark: benchmarks/concoct.benchmark.txt
    reason: Missing output files: data/concoct_bins/done; Input files updated by another job: data/binning_bams/done
    threads: 30
    resources: mem_mb=32000, mem_mib=30518, disk_mb=1000, disk_mib=954, tmpdir=/tmp

Activating conda environment: ../../../../home/ubuntu/mambaforge/envs/aviary/41f4dd6488d47aada1f0da2758069752_
touch: cannot touch 'data/concoct_bins/done': No such file or directory
[Mon Jan  2 12:06:35 2023]
Error in rule concoct:
    jobid: 9
    input: /mnt/d/marbles/assembly/metaSPAdes/sponge_04.scaffolds.metaSPAdes.fasta, data/binning_bams/done
    output: data/concoct_bins/done
    conda-env: /home/ubuntu/mambaforge/envs/aviary/41f4dd6488d47aada1f0da2758069752_
    shell:
        rm -rf data/concoct_*/; mkdir -p data/concoct_working && cut_up_fasta.py /mnt/d/marbles/assembly/metaSPAdes/sponge_04.scaffolds.metaSPAdes.fasta -c 10000 -o 0 --merge_last -b data/concoct_working/contigs_10K.bed > data/concoct_working/contigs_10K.fa && concoct_coverage_table.py data/concoct_working/contigs_10K.bed data/binning_bams/*.bam > data/concoct_working/coverage_table.tsv && concoct --threads 30 -l 1500 --composition_file data/concoct_working/contigs_10K.fa --coverage_file data/concoct_working/coverage_table.tsv -b data/concoct_working/ 2>/dev/null && merge_cutup_clustering.py data/concoct_working/clustering_gt1500.csv > data/concoct_working/clustering_merged.csv && mkdir -p data/concoct_bins && extract_fasta_bins.py /mnt/d/marbles/assembly/metaSPAdes/sponge_04.scaffolds.metaSPAdes.fasta data/concoct_working/clustering_merged.csv --output_path data/concoct_bins/ && touch data/concoct_bins/done || touch data/concoct_bins/done
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
An error occurred
Complete log: .snakemake/log/2023-01-02T113234.913881.snakemake.log
01/02/2023 12:06:35 PM CRITICAL: Command 'snakemake --snakefile /mnt/d/GSN/aviary/aviary/modules/Snakefile --directory /mnt/d/marbles/aviary --jobs 30 --rerun-incomplete   --configfile '/mnt/d/marbles/aviary/config.yaml' --nolock  --conda-frontend mamba --default-resources "tmpdir='/tmp'" --resources mem_mb=256000   --use-conda --conda-prefix /home/ubuntu/mambaforge/envs/aviary/   recover_mags' returned non-zero exit status 1.
```
Attached you can find the snakemake log file. Somehow `concoct` could not create the output folder.
[2023-01-02T113234.913881.snakemake.log](https://github.com/rhysnewell/aviary/files/10331265/2023-01-02T113234.913881.snakemake.log)

**Comment by rhysnewell** [comment]
Hmm, did any of the other binners successfully complete? And is there any sign of the concoct folder existing? If there is perhaps try deleting it and running again. Error like this usually occur when aviary is run from the incorrect folder so the paths get messed up, but I don't see any indication of that occurring here.

Cheers,
Rhys

**Comment by julianzaugg** [comment]
@rhysnewell I believe the numpy version issue is related to this: [https://stackoverflow.com/questions/74852225/attributeerror-module-numpy-has-no-attribute-typedict/74969328#74969328](https://stackoverflow.com/questions/74852225/attributeerror-module-numpy-has-no-attribute-typedict/74969328#74969328)?

**Comment by rhysnewell** [comment]
@julianzaugg you may want to flag this with @chklovski if he isn't already aware of this. The checkm2 environment is using all of the same requirements as listed in the checkm2 setup.py and is pulling from up to date checkm2 code. Not sure where else the numpy issue would be coming from.

**Comment by 0x1d4e** [comment]
I managed to get Aviary to work with these additional changes:
	- Add checkM2 binary location to $PATH'
	- Try to uninstall and reinstall numpy and setuptools in the metaBAT environment
	- Downgrade numpy to 1.23.1 in the Prodigal envirionment regarding the error: `AttributeError: module 'numpy'has no attribute 'bool'`(https://stackoverflow.com/questions/74893742/how-to-solve-attributeerror-module-numpy-has-no-attribute-bool)

The concoct binner still does not work for some reason, probably something to do with my environment (?), so I skip that for now.

**Comment by AroneyS** [comment]
I had the same issue installing Aviary from conda and running `aviary recover` with just metabat2: `AttributeError: module 'numpy' has no attribute 'typeDict'`.
I wonder if it is related to the h5py version being frozen (https://github.com/rhysnewell/aviary/blob/eb4825f2af28d96ca8a92e1e86454fe461ea8024/aviary/envs/checkm2.yaml#LL9C1-L9C16), see https://github.com/tensorflow/tensorflow/issues/59513#issuecomment-1457336883.

I entered the CheckM2 env and ran `conda update h5py`, which updated it to v3.8.0 (full changes below). Rerunning Aviary recover initially started CheckM2 (so bypassing the error) but then had another error later with `split`, not recognising the expand argument.

I wonder if we should simplify the yaml file to just `checkm2`?


CheckM2 env changes
```
The following packages will be UPDATED:

  curl                                     8.1.1-h409715c_0 --> 8.1.2-h409715c_0 
  flatbuffers                             23.3.3-hcb278e6_0 --> 23.3.3-hcb278e6_1 
  google-auth                           2.17.3-pyh1a96a4e_0 --> 2.19.0-pyh1a96a4e_0 
  h5py                        2.10.0-nompi_py39h98ba4bc_106 --> 3.8.0-nompi_py39h89bf01e_101 
  hdf5                            1.10.6-nompi_h3c11f04_101 --> 1.14.0-nompi_hb72d44e_103 
  libblas                                  3.9.0-8_openblas --> 3.9.0-16_linux64_openblas 
  libcblas                                 3.9.0-8_openblas --> 3.9.0-16_linux64_openblas 
  libcurl                                  8.1.1-h409715c_0 --> 8.1.2-h409715c_0 
  libgfortran-ng                          7.5.0-h14aa051_20 --> 12.2.0-h69a702a_19 
  liblapack                                3.9.0-8_openblas --> 3.9.0-16_linux64_openblas 
  libopenblas                    0.3.12-pthreads_hb3c22a3_1 --> 0.3.21-pthreads_h78a6416_3 
  openssl                                  3.1.0-hd590300_3 --> 3.1.1-hd590300_0 
  python-flatbuffers                   23.1.21-pyhd8ed1ab_0 --> 23.5.26-pyhd8ed1ab_0 
  scipy                                1.5.3-py39hf3f25e7_0 --> 1.10.1-py39h6183b62_3 
  typing-extensions                        4.6.1-hd8ed1ab_0 --> 4.6.2-hd8ed1ab_0 
  typing_extensions                      4.6.1-pyha770c72_0 --> 4.6.2-pyha770c72_0 
  yarl                                 1.9.1-py39hd1e30aa_0 --> 1.9.2-py39hd1e30aa_0 

The following packages will be DOWNGRADED:

  urllib3                                2.0.2-pyhd8ed1ab_0 --> 1.26.15-pyhd8ed1ab_0
```

**Comment by rhysnewell** [comment]
I believe this issue is fixed on the `medaka` branch: https://github.com/rhysnewell/aviary/commit/6886682ba497c81880112082926ad1eb484ec6ac

Medaka has been merged into the Dev branch, except merging Dev into main is blocked as it requires approval: https://github.com/rhysnewell/aviary/pull/96

**Comment by AroneyS** [comment]
Is there a reason to not switch to the conda version of CheckM2, now that it is out?
https://anaconda.org/bioconda/checkm2

**Comment by rhysnewell** [comment]
Pretty sure that the conda version of checkm2 is out of date and may still have requirement issues

**Comment by rhysnewell** [comment]
Should be fixed in latest release: https://github.com/rhysnewell/aviary/releases/tag/v0.6.0
