### ISSUE TITLE
rule singlem_pipe_reads: AttributeError: module 'contextlib' has no attribute 'asynccontextmanager'

### ISSUE THREAD

**Issue by julianzaugg** [rhysnewell/aviary#93]
Running Aviary (ver. 0.5.7) recover produced the following error in `rule singlem_pipe_reads`:

```
Activating conda environment: ../../../../../../home/USER/.conda/envs/f9f764082a65aaf12cd66794e44fb7c3_
Traceback (most recent call last):
  File "AVIARY_OUT_DIR.snakemake/scripts/tmp3ctiegic.singlem_reads.py", line 3, in <module>
    import sys; sys.path.extend(['/opt/centos7/sw/miniconda3/envs/aviary_0.5.7/lib/python3.10/site-packages', '/srv/home/USER/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpm5elmjmr/file/opt/centos7/sw/miniconda3/envs/aviary_0.5.7/lib/python3.10/site-packages/aviary/modules/binning/../../scripts', '/opt/centos7/sw/miniconda3/envs/aviary_0.5.7/lib/python3.10/site-packages/aviary/modules/binning/../../scripts']); import pickle; snakemake = pickle.loads(b'\x80\x04\x95\x8b\x13\x00\x00\x00\x00\x00\x00\x8c\x10snakemake.script\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94\x8c\x0csnakemake.io\x94\x8c\nInputFiles\x94\x93\x94)\x81\x94}\x94(\x8c\x06_names\x94}\x94\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x0f\x8c\tfunctools\x94\x8c\x07partial\x94\x93\x94h\x06\x8c\x19Namedlist._used_attribute\x94\x93\x94\x85\x94R\x94(h\x15)}\x94\x8c\x05_name\x94h\x0fsNt\x94bh\x10h\x13h\x15\x85\x94R\x94(h\x15)}\x94h\x19h\x10sNt\x94bub\x8c\x06output\x94h\x06\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94\x8c2data/singlem_out/metagenome.combined_otu_table.csv\x94a}\x94(h\x0b}\x94h\r]\x94(h\x0fh\x10eh\x0fh\x13h\x15\x85\x94R\x94(h\x15)}\x94h\x19h\x0fsNt\x94bh\x10h\x13h\x15\x85\x94R\x94(h\x15)}\x94h\x19h\x10sNt\x94bub\x8c\x06params\x94h\x06\x8c\x06Params\x94\x93\x94)\x81\x94}\x94(h\x0b}\x94h\r]\x94(h\x0fh\x10eh\x0fh\x13h\x15\x85\x94R\x94(h\x15)}\x94h\x19h\x0fsNt\x94bh\x10h\x13h\x15\x85\x94R\x94(h\x15)}\x94h\x19h\x10sNt\x94bub\x8c\twildcards\x94h\x06\x8c\tWildcards\x94\x93\x94)\x81\x94}\x94(h\x0b}\x94h\r]\x94(h\x0fh\x10eh\x0fh\x13h\x15\x85\x94R\x94(h\x15)}\x94h\x19h\x0fsNt\x94bh\x10h\x13h\x15\x85\x94R\x94(h\x15)}\x94h\x19h\x10sNt\x94bub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x06\x8c\tResources\x94\x93\x94)\x81\x94(K\x01K\x01M\xe8\x03M\xba\x03M\xe8\x03M\xba\x03\x8c\x04/tmp\x94e}\x94(h\x0b}\x94(\x8c\x06_cores\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06mem_mb\x94K\x02N\x86\x94\x8c\x07mem_mib\x94K\x03N\x86\x94\x8c\x07disk_mb\x94K\x04N\x86\x94\x8c\x08disk_mib\x94K\x05N\x86\x94\x8c\x06tmpdir\x94K\x06N\x86\x94uh\r]\x94(h\x0fh\x10eh\x0fh\x13h\x15\x85\x94R\x94(h\x15)}\x94h\x19h\x0fsNt\x94bh\x10h\x13h\x15\x85\x94R\x94(h\x15)}\x94h\x19h\x10sNt\x94bhUK\x01hWK\x01hYM\xe8\x03h[M\xba\x03h]M\xe8\x03h_M\xba\x03hahRub\x8c\x03log\x94h\x06\x8c\x03Log\x94\x93\x94)\x81\x94}\x94(h\x0b}\x94h\r]\x94(h\x0fh\x10eh\x0fh\x13h\x15\x85\x94R\x94(h\x15)}\x94h\x19h\x0fsNt\x94bh\x10h\x13h\x15\x85\x94R\x94(h\x15)}\x94h\x19h\x10sNt\x94bub\x8c\x06config\x94}\x94(\x8c\x05fasta\x94]\x94\x8cJ/srv/projects3/IMOS/Julian_temp/3_scaffolds/farquaharson_2.scaffolds.fasta\x94a\x8c\nlong_reads\x94\x8c\x04none\x94\x8c\x0elong_read_type\x94\x8c\x03ont\x94\x8c\rshort_reads_1\x94]\x94(\x8ck/srv/projects/julian/IMOS/Julian_temp/2_reads/farquaharson_1__BBG6418_21S000448_R1_allRunsCombined.fastq.gz\x94\x8ck/srv/projects/julian/IMOS/Julian_temp/2_reads/farquaharson_2__BBG6419_22S000874_R1_allRunsCombined.fastq.gz\x94\x8ck/srv/projects/julian/IMOS/Julian_temp/2_reads/farquaharson_3__BBG6420_21S000450_R1_allRunsCombined.fastq.gz\x94\x8ck/srv/projects/julian/IMOS/Julian_temp/2_reads/farquaharson_4__BBG6421_22S000875_R1_allRunsCombined.fastq.gz\x94\x8ci/srv/projects/julian/IMOS/Julian_temp/2_reads/agincourt1_1__BBG6450_21S000073_R1_allRunsCombined.fastq.gz\x94\x8ci/srv/projects/julian/IMOS/Julian_temp/2_reads/agincourt1_2__BBG6451_21S000475_R1_allRunsCombined.fastq.gz\x94\x8ci/srv/projects/julian/IMOS/Julian_temp/2_reads/agincourt1_3__BBG6452_22S000879_R1_allRunsCombined.fastq.gz\x94\x8ci/srv/projects/julian/IMOS/Julian_temp/2_reads/agincourt1_4__BBG6453_21S000477_R1_allRunsCombined.fastq.gz\x94\x8ch/srv/projects/julian/IMOS/Julian_temp/2_reads/arlington_1__BBG6454_21S000478_R1_allRunsCombined.fastq.gz\x94\x8ch/srv/projects/julian/IMOS/Julian_temp/2_reads/arlington_2__BBG6455_21S000479_R1_allRunsCombined.fastq.gz\x94\x8ch/srv/projects/julian/IMOS/Julian_temp/2_reads/arlington_3__BBG6456_21S000480_R1_allRunsCombined.fastq.gz\x94\x8ch/srv/projects/julian/IMOS/Julian_temp/2_reads/arlington_4__BBG6457_21S000074_R1_allRunsCombined.fastq.gz\x94e\x8c\rshort_reads_2\x94]\x94(\x8ck/srv/projects/julian/IMOS/Julian_temp/2_reads/farquaharson_1__BBG6418_21S000448_R2_allRunsCombined.fastq.gz\x94\x8ck/srv/projects/julian/IMOS/Julian_temp/2_reads/farquaharson_2__BBG6419_22S000874_R2_allRunsCombined.fastq.gz\x94\x8ck/srv/projects/julian/IMOS/Julian_temp/2_reads/farquaharson_3__BBG6420_21S000450_R2_allRunsCombined.fastq.gz\x94\x8ck/srv/projects/julian/IMOS/Julian_temp/2_reads/farquaharson_4__BBG6421_22S000875_R2_allRunsCombined.fastq.gz\x94\x8ci/srv/projects/julian/IMOS/Julian_temp/2_reads/agincourt1_1__BBG6450_21S000073_R2_allRunsCombined.fastq.gz\x94\x8ci/srv/projects/julian/IMOS/Julian_temp/2_reads/agincourt1_2__BBG6451_21S000475_R2_allRunsCombined.fastq.gz\x94\x8ci/srv/projects/julian/IMOS/Julian_temp/2_reads/agincourt1_3__BBG6452_22S000879_R2_allRunsCombined.fastq.gz\x94\x8ci/srv/projects/julian/IMOS/Julian_temp/2_reads/agincourt1_4__BBG6453_21S000477_R2_allRunsCombined.fastq.gz\x94\x8ch/srv/projects/julian/IMOS/Julian_temp/2_reads/arlington_1__BBG6454_21S000478_R2_allRunsCombined.fastq.gz\x94\x8ch/srv/projects/julian/IMOS/Julian_temp/2_reads/arlington_2__BBG6455_21S000479_R2_allRunsCombined.fastq.gz\x94\x8ch/srv/projects/julian/IMOS/Julian_temp/2_reads/arlington_3__BBG6456_21S000480_R2_allRunsCombined.fastq.gz\x94\x8ch/srv/projects/julian/IMOS/Julian_temp/2_reads/arlington_4__BBG6457_21S000074_R2_allRunsCombined.fastq.gz\x94e\x8c\x0fmin_contig_size\x94M\xdc\x05\x8c\x0cmin_bin_size\x94J@\r\x03\x00\x8c\x0bmax_threads\x94K"\x8c\x0fpplacer_threads\x94K"\x8c\nmax_memory\x94M\x90\x01\x8c\x0bgenome_size\x94J@KL\x00\x8c\x10reference_filter\x94\x8c\x04none\x94\x8c\x0fstrain_analysis\x94\x89\x8c\x10unassembled_long\x94\x8c\x04none\x94\x8c\x04mags\x94\x8c\x04none\x94\x8c\rmag_directory\x94\x8c\x0fbins/final_bins\x94\x8c\rmag_extension\x94\x8c\x03fna\x94\x8c\x0finstrain_params\x94}\x94\x8c\x11profile_read_list\x94\x8c\x04none\x94\x8c\x14min_long_read_length\x94M\xf4\x01\x8c\x0ckeep_percent\x94Kc\x8c\nmin_mean_q\x94K(\x8c\x0bguppy_model\x94\x8c\x12r941_min_high_g360\x94\x8c\rgtdbtk_folder\x94\x8c%/srv/db/gtdbtk/official/release207_v2\x94\x8c\x0cbusco_folder\x94\x8c\x04none\x94\x8c\x11checkm2_db_folder\x94\x8c,/srv/db/checkm2_data/0.1.3/CheckM2_database/\x94\x8c\reggnog_folder\x94\x8c\x12/srv/db/eggnog/5.0\x94\x8c\x0evirsorter_data\x94\x8c\x04none\x94\x8c\x05email\x94\x8c\x11somename@email.co\x94\x8c\x03gsa\x94]\x94\x8c0/srv/projects3/IMOS/Julian_temp/3_scaffolds/none\x94a\x8c\x0cgsa_mappings\x94\x8c\x04none\x94\x8c\rsemibin_model\x94\x8c\x06global\x94\x8c\nkmer_sizes\x94]\x94\x8c\x04auto\x94a\x8c\x0buse_megahit\x94\x89\x8c\ncoassemble\x94\x88\x8c\x0cmin_cov_long\x94K\x14\x8c\rmin_cov_short\x94K\x03\x8c\x12exclude_contig_cov\x94Kd\x8c\x13exclude_contig_size\x94M\xa8a\x8c\x10long_contig_size\x94J\xa0\x86\x01\x00\x8c\x12use_checkm2_scores\x94\x89\x8c\rprevious_runs\x94\x8c\x04none\x94\x8c\x10min_completeness\x94\x8c\x04none\x94\x8c\x11max_contamination\x94\x8c\x04none\x94\x8c\x03ani\x94\x8c\x04none\x94\x8c\x0eprecluster_ani\x94\x8c\x04none\x94\x8c\x11precluster_method\x94\x8c\x04none\x94\x8c\x0bpggb_params\x94\x8c\x04none\x94\x8c\x06tmpdir\x94\x8c\x04/tmp\x94u\x8c\x04rule\x94\x8c\x12singlem_pipe_reads\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8cn/opt/centos7/sw/miniconda3/envs/aviary_0.5.7/lib/python3.10/site-packages/aviary/modules/binning/../../scripts\x94ub.'); from snakemake.logging import logger; logger.printshellcmds = False; __real_file__ = __file__; __file__ = '/opt/centos7/sw/miniconda3/envs/aviary_0.5.7/lib/python3.10/site-packages/aviary/scripts/singlem_reads.py';
  File "/opt/centos7/sw/miniconda3/envs/aviary_0.5.7/lib/python3.10/site-packages/snakemake/__init__.py", line 22, in <module>
    from snakemake.target_jobs import parse_target_jobs_cli_args
  File "/opt/centos7/sw/miniconda3/envs/aviary_0.5.7/lib/python3.10/site-packages/snakemake/target_jobs.py", line 4, in <module>
    from snakemake.common import parse_key_value_arg
  File "/opt/centos7/sw/miniconda3/envs/aviary_0.5.7/lib/python3.10/site-packages/snakemake/common/__init__.py", line 284, in <module>
    @contextlib.asynccontextmanager
AttributeError: module 'contextlib' has no attribute 'asynccontextmanager'
[Thu Feb 16 20:11:33 2023]
Error in rule singlem_pipe_reads:
    jobid: 28
    output: data/singlem_out/metagenome.combined_otu_table.csv
    conda-env: /srv/home/USER/.conda/envs/f9f764082a65aaf12cd66794e44fb7c3_

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 34
Rules claiming more threads will be scaled down.
Provided resources: mem_mb=1000, mem_mib=954, disk_mb=1000, disk_mib=954
Select jobs to execute...
[Thu Feb 16 20:11:38 2023]
Finished job 1.
21 of 24 steps (88%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-02-15T055352.041746.snakemake.log
An error occurred
02/16/2023 08:11:38 PM CRITICAL: Command 'snakemake --snakefile /opt/centos7/sw/miniconda3/envs/aviary_0.5.7/lib/python3.10/site-packages/aviary/modules/Snakefile --directory AVIARY_OUT_DIR --jobs 34 --rerun-incomplete   --configfile 'AVIARY_OUT_DIRconfig.yaml' --nolock  --conda-frontend mamba --default-resources "tmpdir='/tmp'" --resources mem_mb=409600   --use-conda --conda-prefix /srv/home/USER/.conda/envs/   recover_mags' returned non-zero exit status 1.
```

Can avoid by using `rule recover_mags_no_singlem`. From a quick look, might be issue with how SnakeMake handles threading [https://github.com/snakemake/snakemake/commit/50b8f1609a597dc9f25d2fd86c9cdda531bdc041](https://github.com/snakemake/snakemake/commit/50b8f1609a597dc9f25d2fd86c9cdda531bdc041)?

**Comment by rhysnewell** [comment]
That's a weird one. That rule isn't doing anything fancy, so not sure why it is halting there. What version of Snakemake are you using?

**Comment by julianzaugg** [comment]
In this case, Aviary is using `ver. 7.22.0`

**Comment by rhysnewell** [comment]
Does the error still occur if you downgrade to Snakemake v7.17.2? Looks like v7.18 onwards have this change. A bunch of releases all happened back to back in rapid succession for Snakemake

**Comment by rhysnewell** [comment]
This doesn't seem to be an issue any longer, if it reoccurs then reopen the issue
